/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ProdutoRouteImport } from './routes/produto'
import { Route as NegocioRouteImport } from './routes/negocio'
import { Route as MercadoRouteImport } from './routes/mercado'
import { Route as EquipaRouteImport } from './routes/equipa'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppMentoriaRouteImport } from './routes/app.mentoria'
import { Route as AppIaRouteImport } from './routes/app.ia'
import { Route as AppCronogramaRouteImport } from './routes/app.cronograma'
import { Route as AppBibliotecaRouteImport } from './routes/app.biblioteca'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoRoute = ProdutoRouteImport.update({
  id: '/produto',
  path: '/produto',
  getParentRoute: () => rootRouteImport,
} as any)
const NegocioRoute = NegocioRouteImport.update({
  id: '/negocio',
  path: '/negocio',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoRoute = MercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipaRoute = EquipaRouteImport.update({
  id: '/equipa',
  path: '/equipa',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMentoriaRoute = AppMentoriaRouteImport.update({
  id: '/mentoria',
  path: '/mentoria',
  getParentRoute: () => AppRoute,
} as any)
const AppIaRoute = AppIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AppRoute,
} as any)
const AppCronogramaRoute = AppCronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => AppRoute,
} as any)
const AppBibliotecaRoute = AppBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/equipa': typeof EquipaRoute
  '/mercado': typeof MercadoRoute
  '/negocio': typeof NegocioRoute
  '/produto': typeof ProdutoRoute
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/biblioteca': typeof AppBibliotecaRoute
  '/app/cronograma': typeof AppCronogramaRoute
  '/app/ia': typeof AppIaRoute
  '/app/mentoria': typeof AppMentoriaRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/equipa': typeof EquipaRoute
  '/mercado': typeof MercadoRoute
  '/negocio': typeof NegocioRoute
  '/produto': typeof ProdutoRoute
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/biblioteca': typeof AppBibliotecaRoute
  '/app/cronograma': typeof AppCronogramaRoute
  '/app/ia': typeof AppIaRoute
  '/app/mentoria': typeof AppMentoriaRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/equipa': typeof EquipaRoute
  '/mercado': typeof MercadoRoute
  '/negocio': typeof NegocioRoute
  '/produto': typeof ProdutoRoute
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/biblioteca': typeof AppBibliotecaRoute
  '/app/cronograma': typeof AppCronogramaRoute
  '/app/ia': typeof AppIaRoute
  '/app/mentoria': typeof AppMentoriaRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/contacto'
    | '/equipa'
    | '/mercado'
    | '/negocio'
    | '/produto'
    | '/roadmap'
    | '/sitemap.xml'
    | '/app/biblioteca'
    | '/app/cronograma'
    | '/app/ia'
    | '/app/mentoria'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/equipa'
    | '/mercado'
    | '/negocio'
    | '/produto'
    | '/roadmap'
    | '/sitemap.xml'
    | '/app/biblioteca'
    | '/app/cronograma'
    | '/app/ia'
    | '/app/mentoria'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/contacto'
    | '/equipa'
    | '/mercado'
    | '/negocio'
    | '/produto'
    | '/roadmap'
    | '/sitemap.xml'
    | '/app/biblioteca'
    | '/app/cronograma'
    | '/app/ia'
    | '/app/mentoria'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  EquipaRoute: typeof EquipaRoute
  MercadoRoute: typeof MercadoRoute
  NegocioRoute: typeof NegocioRoute
  ProdutoRoute: typeof ProdutoRoute
  RoadmapRoute: typeof RoadmapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto': {
      id: '/produto'
      path: '/produto'
      fullPath: '/produto'
      preLoaderRoute: typeof ProdutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negocio': {
      id: '/negocio'
      path: '/negocio'
      fullPath: '/negocio'
      preLoaderRoute: typeof NegocioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado': {
      id: '/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof MercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipa': {
      id: '/equipa'
      path: '/equipa'
      fullPath: '/equipa'
      preLoaderRoute: typeof EquipaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mentoria': {
      id: '/app/mentoria'
      path: '/mentoria'
      fullPath: '/app/mentoria'
      preLoaderRoute: typeof AppMentoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ia': {
      id: '/app/ia'
      path: '/ia'
      fullPath: '/app/ia'
      preLoaderRoute: typeof AppIaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cronograma': {
      id: '/app/cronograma'
      path: '/cronograma'
      fullPath: '/app/cronograma'
      preLoaderRoute: typeof AppCronogramaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/biblioteca': {
      id: '/app/biblioteca'
      path: '/biblioteca'
      fullPath: '/app/biblioteca'
      preLoaderRoute: typeof AppBibliotecaRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBibliotecaRoute: typeof AppBibliotecaRoute
  AppCronogramaRoute: typeof AppCronogramaRoute
  AppIaRoute: typeof AppIaRoute
  AppMentoriaRoute: typeof AppMentoriaRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBibliotecaRoute: AppBibliotecaRoute,
  AppCronogramaRoute: AppCronogramaRoute,
  AppIaRoute: AppIaRoute,
  AppMentoriaRoute: AppMentoriaRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ContactoRoute: ContactoRoute,
  EquipaRoute: EquipaRoute,
  MercadoRoute: MercadoRoute,
  NegocioRoute: NegocioRoute,
  ProdutoRoute: ProdutoRoute,
  RoadmapRoute: RoadmapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
